version: '2.4'
services:
  sourcegraph-frontend-0:
    cpus: 0.8
  sourcegraph-frontend-internal:
    cpus: 0.8
  gitserver-0:
    cpus: 0.5
  searcher-0:
    cpus: 0.5
  symbols-0:
    cpus: 0.5
  repo-updater:
    cpus: 0.5
  precise-code-intel-worker:
    cpus: 0.5
  worker:
    cpus: 0.5
