version: '3.7'
services:
  caddy:
    volumes:
      - /mnt/docker-data/sourcegraph-data/caddy:/etc/caddy
  gitserver-0:
    volumes:
      - /mnt/docker-data/sourcegraph-data/gitserver-0:/data/repos
  pgsql:
    volumes:
      - /mnt/docker-data/sourcegraph-data/pgsql:/var/lib/postgresql/data
  codeintel-db:
    volumes:
      - /mnt/docker-data/sourcegraph-data/codeintel-db:/var/lib/postgresql/data
  codeinsights-db:
    volumes:
      - /mnt/docker-data/sourcegraph-data/codeinsights-db:/var/lib/postgresql/data
  redis-cache:
    volumes:
      - /mnt/docker-data/sourcegraph-data/redis-cache:/redis-data
  redis-store:
    volumes:
      - /mnt/docker-data/sourcegraph-data/redis-store:/redis-data
  blobstore:
    volumes:
      - /mnt/docker-data/sourcegraph-data/blobstore:/data
  zoekt-indexserver-0:
    volumes:
      - /mnt/docker-data/sourcegraph-data/zoekt:/data/index
  zoekt-webserver-0:
    volumes:
      - /mnt/docker-data/sourcegraph-data/zoekt:/data/index
  prometheus:
    volumes:
      - /mnt/docker-data/sourcegraph-data/prometheus:/prometheus
      
# Override/disable the volumes defined in the main docker-compose.yaml file
volumes:
  codeinsights-db:
    driver: local
    driver_opts:
      type: none
      device: /mnt/docker-data/sourcegraph-data/codeinsights-db
      o: bind
